name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Get the version
        id: get-version
        run: |
          version=$(echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-)
          echo ::set-output name=VERSION::$version
        shell: bash
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Update version
        run: |
          git config --global user.name 'polarker'
          git config --global user.email 'polarker@users.noreply.github.com'
          npm --no-git-tag-version version ${{ steps.get-version.outputs.VERSION }}
      - name: Commit version
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Bump to ${{ steps.get-version.outputs.VERSION }}"
          git push origin HEAD:master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get-version.outputs.VERSION }}
          release_name: v${{ steps.get-version.outputs.VERSION }}
          body: Some solid code
          draft: false
          prerelease: false
